/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedGateRouteImport } from './routes/_authenticated/gate'
import { Route as AuthenticatedApprovedRouteImport } from './routes/_authenticated/_approved'
import { Route as AuthenticatedApprovedTicketsRouteImport } from './routes/_authenticated/_approved/tickets'
import { Route as AuthenticatedApprovedHomeRouteImport } from './routes/_authenticated/_approved/home'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGateRoute = AuthenticatedGateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovedRoute = AuthenticatedApprovedRouteImport.update({
  id: '/_approved',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovedTicketsRoute =
  AuthenticatedApprovedTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedApprovedRoute,
  } as any)
const AuthenticatedApprovedHomeRoute =
  AuthenticatedApprovedHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => AuthenticatedApprovedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/gate': typeof AuthenticatedGateRoute
  '/home': typeof AuthenticatedApprovedHomeRoute
  '/tickets': typeof AuthenticatedApprovedTicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/gate': typeof AuthenticatedGateRoute
  '/home': typeof AuthenticatedApprovedHomeRoute
  '/tickets': typeof AuthenticatedApprovedTicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/_approved': typeof AuthenticatedApprovedRouteWithChildren
  '/_authenticated/gate': typeof AuthenticatedGateRoute
  '/_authenticated/_approved/home': typeof AuthenticatedApprovedHomeRoute
  '/_authenticated/_approved/tickets': typeof AuthenticatedApprovedTicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/gate' | '/home' | '/tickets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/gate' | '/home' | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/_approved'
    | '/_authenticated/gate'
    | '/_authenticated/_approved/home'
    | '/_authenticated/_approved/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gate': {
      id: '/_authenticated/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof AuthenticatedGateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_approved': {
      id: '/_authenticated/_approved'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedApprovedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_approved/tickets': {
      id: '/_authenticated/_approved/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedApprovedTicketsRouteImport
      parentRoute: typeof AuthenticatedApprovedRoute
    }
    '/_authenticated/_approved/home': {
      id: '/_authenticated/_approved/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedApprovedHomeRouteImport
      parentRoute: typeof AuthenticatedApprovedRoute
    }
  }
}

interface AuthenticatedApprovedRouteChildren {
  AuthenticatedApprovedHomeRoute: typeof AuthenticatedApprovedHomeRoute
  AuthenticatedApprovedTicketsRoute: typeof AuthenticatedApprovedTicketsRoute
}

const AuthenticatedApprovedRouteChildren: AuthenticatedApprovedRouteChildren = {
  AuthenticatedApprovedHomeRoute: AuthenticatedApprovedHomeRoute,
  AuthenticatedApprovedTicketsRoute: AuthenticatedApprovedTicketsRoute,
}

const AuthenticatedApprovedRouteWithChildren =
  AuthenticatedApprovedRoute._addFileChildren(
    AuthenticatedApprovedRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedApprovedRoute: typeof AuthenticatedApprovedRouteWithChildren
  AuthenticatedGateRoute: typeof AuthenticatedGateRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApprovedRoute: AuthenticatedApprovedRouteWithChildren,
  AuthenticatedGateRoute: AuthenticatedGateRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
